title: The Carpet Cleaning Company
business_name: The Carpet Cleaning Company
phone: 07802563213
email: info@thecarpetcleaningcrew.co.uk
website: https://www.thecarpetcleaningcrew.co.uk
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
service_area: Shrewsbury, Telford, Hereford, Ludlow and surrounding areas
location_list: Shrewsbury, Telford, Hereford, Ludlow and surrounding towns
logo_url: assets/logo-tccc.svg
baseurl: ''
url: ''
phone_link: '+447802563213'
contact_name: Paul
map_query: Shropshire and Herefordshire UK
