title: JW Carpet Care
business_name: JW Carpet Care
phone: "07838231389"
email: "infojwcarpetcare@gmail.com"
website: "https://jwcarpetcare.co.uk"
facebook_url: "https://www.facebook.com/profile.php?id=61565031206102"
instagram_url: "https://www.instagram.com/james.wilson69/"
service_area: "Worcestershire and the West Midlands"
location_list: "Worcester, Bromsgrove, Kidderminster, Redditch and surrounding areas"
logo_url: "https://jwcarpetcare.co.uk/wp-content/uploads/2022/01/Untitled-500-%C3%97-300-px-e1690358088999.png"
baseurl: ""
url: ""

phone_link: "+447838231389"

contact_name: "James"
map_query: "Worcestershire UK"
